/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Gundyr API
 * OpenAPI spec version: 1.0.0
 */
import type { GetCheckSession200User } from './getCheckSession200User';

export type GetCheckSession200 = {
  user: GetCheckSession200User;
};
