/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Gundyr API
 * OpenAPI spec version: 1.0.0
 */
import type { GetGetFiles200FilesItem } from './getGetFiles200FilesItem';

export type GetGetFiles200 = {
  files: GetGetFiles200FilesItem[];
};
