/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Gundyr API
 * OpenAPI spec version: 1.0.0
 */
import type { GetGetQuota200Quota } from './getGetQuota200Quota';

export type GetGetQuota200 = {
  quota: GetGetQuota200Quota;
};
