/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Gundyr API
 * OpenAPI spec version: 1.0.0
 */
import type { PostPinFile200File } from './postPinFile200File';

export type PostPinFile200 = {
  file: PostPinFile200File;
};
