/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Gundyr API
 * OpenAPI spec version: 1.0.0
 */

export type PostAuth200AuthenticationType = typeof PostAuth200AuthenticationType[keyof typeof PostAuth200AuthenticationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuth200AuthenticationType = {
  Bearer: 'Bearer',
} as const;
