/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Gundyr API
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuth200AuthenticationType } from './postAuth200AuthenticationType';

export type PostAuth200 = {
  token: string;
  authenticationType: PostAuth200AuthenticationType;
};
