/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Gundyr API
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthBody = {
  /** in hex */
  payload: string;
  /** in hex */
  signature: string;
  /** in hex */
  address: string;
};
